global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
  - 'rules/*.yml'

scrape_configs:
  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['dcgm-exporter:9400']
    scrape_interval: 1s
    metric_relabel_configs:
      - source_labels: [gpu]
        target_label: gpu_id
        regex: (.*)
        replacement: ${1}

  - job_name: 'ml-workload'
    static_configs:
      - targets: ['ml-workload:8000']
    scrape_interval: 1s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []