global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'rules/*.yml'

scrape_configs:
  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['dcgm-exporter:9400']
    metric_relabel_configs:
      - source_labels: [gpu]
        regex: (.*)
        target_label: gpu_index
        replacement: '${1}'

  - job_name: 'ml-workload'
    static_configs:
      - targets: ['ml-workload:8000']
    metric_relabel_configs:
      - source_labels: [model_name]
        regex: (.*)
        target_label: model
        replacement: '${1}'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []